---

- name: Install latest stable neovim
  hosts: localhost
  become: true

  tasks:

  - name: Download and extract neovim tar file
    unarchive:
      src: https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
      remote_src: yes
      dest: /opt/

  - name: Rename nvim-linux64 folder to neovim
    command: mv /opt/nvim-linux64 /opt/neovim

  - name: Link nvim binary to /usr/bin
    file:
      src: /opt/neovim/bin/nvim
      dest: /usr/bin/nvim
      state: link
