# https://github.com/ThePrimeagen/ansible/blob/master/local.yml

- hosts: localhost
  connection: local
  roles:
    - role: compscidr.gpg
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
    gpg_key_src: "./.gnupg/gpg-key.asc"
  vars_files:
    - "./vars/secrets.yml"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
  - ansible.builtin.import_tasks: tasks/core-setup.yml
  - ansible.builtin.import_tasks: tasks/ssh.yml
  - ansible.builtin.import_tasks: tasks/gpg-setup.yml
  - ansible.builtin.import_tasks: tasks/git-setup.yml
  - ansible.builtin.import_tasks: tasks/zsh-setup.yml
  - ansible.builtin.import_tasks: tasks/dotfiles.yml
  - ansible.builtin.import_tasks: tasks/node-setup.yml
  - ansible.builtin.import_tasks: tasks/npm-packages.yml
  - ansible.builtin.import_tasks: tasks/nvim-setup.yml
  - ansible.builtin.import_tasks: tasks/flutter-setup.yml
  - ansible.builtin.import_tasks: tasks/chrome-setup.yml
  - ansible.builtin.import_tasks: tasks/vivaldi-setup.yml
  - ansible.builtin.import_tasks: tasks/sway-setup.yml
      #    - include: tasks/personal-projects.yml
      #    - include: tasks/debugger.yml
      #    - include: tasks/productivity-tools.yml
      #    - include: tasks/lsp.yml

