- name: Install ZSH
  become: true
  apt: name=zsh
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]
    
- name: Set login shell to zsh
  shell: usermod --shell /bin/zsh hambergerpls
  become: true
  tags: *tags_for_zsh_tasks

- name: Check that starship.toml exists
  stat:
    path: /home/hambergerpls/.config/starship.toml
  register: starship_toml
  tags: *tags_for_zsh_tasks

- name: Download starship
  shell: curl -sS https://starship.rs/install.sh > ~/.starship-installer && chmod +x ~/.starship-installer
  tags: *tags_for_zsh_tasks

- name: Install starship
  expect:
    command: sh /home/hambergerpls/.starship-installer
    responses:
      y/N: 'y'
      (?i)password: "{{ ansible_become_password }}"
  become: true
  become_user: hambergerpls
  when: starship_toml.stat.exists == False
  tags: *tags_for_zsh_tasks
